package Fake

import (
	"github.com/google/uuid"
)

type IFake interface {
	RandomBoolean() bool
	RandomInt() int
	RandomStringMaxLenght(l int) string
	RandomFloatBetween(maxDecimals, min, max int) float64
	RandomIntBetween(min, max int) int
	RandomUUID() uuid.UUID
	CurrentISOTimestamp() string
	CurrentTimestamp() int64
	RandomGuid() uuid.UUID
	RandomAddressLongitude() float64
	RandomAddressLatitude() float64
	RandomAddressCountry() string
	RandomAddressStreetAddress() string
	RandomAddresStreetName() string
	RandomAddressCity() string
	RandomPersonNameSuffix() string
	RandomPersonNamePrefix() string
	RandomPersonFullName() string
	RandomPersonLastName() string
	RandomPersonFirstName() string
	RandomUserAgent() string
	RandomLocale() string
	RandomPassword() string
	RandomMACAddress() string
	RandomIP() string
	RandomSafeColorHex() string
	RandomSafeColorName() string
	RandomDateFuture() string
	RandomDatePast() string
	RandomDateRecent() string
	RandomLoremWord() string
	RandomLoremWords() string
	RandomLoremSentence() string
	RandomPhrase() string
	RandomLoremSentences() string
	RandomLoremLines() string
	RandomLoremParagraph() string
	RandomLoremText() string
	RandomLoremParagraphs() string
	RandomLoremSlug() string
	RandomNoun() string
	RandomVerb() string
	RandomIngVerb() string
	RandomAdjective() string
	RandomWord() string
	RandomWords() string
	RandomDepartment() string
	RandomProductName() string
	RandomProductMaterial() string
	RandomProductAdjective() string
	RandomProduct() string
	RandomPrice() string
	RandomFilePath() string
	RandomMimeType() string
	RandomDirectoryPath() string
	RandomCommonFileExtension() string
	RandomCommonFileType() string
	RandomCommonFileName() string
	RandomFileType() string
	RandomFileExtension() string
	RandomFileName() string
	RandomUrl() string
	RandomUsername() string
	RandomExampleEmail() string
	RandomEmail() string
	RandomDomainWord() string
	RandomDomainSuffix() string
	RandomDomainName() string
	RandomMonth() string
	RandomWeekday() string
	RandomDatabaseColumn() string
	RandomDatabaseType() string
	RandomDatabaseCollation() string
	RandomDatabaseEngine() string
	RandomCatchPhrase() string
	RandomCatchPhraseAdjective() string
	RandomCatchPhraseDescriptor() string
	RandomCatchPhraseNoun() string
	RandomBsNoun() string
	RandomBsBuzzWord() string
	RandomBsAdjective() string
	RandomBs() string
	RandomCompanySuffix() string
	RandomCompanyName() string
	RandomBitcoin() string
	RandomCurrencySymbol() string
	RandomCurrencyCode() string
	RandomCurrencyName() string
	RandomTransactionType() string
	RandomCreditCardMask() string
	RandomBankAccountName() string
	RandomBankAccountBic() string
	RandomBankAccountIban() string
	RandomBankAccount() string
	RandomDataImageUri() string
	RandomAvatarImage() string
	RandomImageURL() string
	RandomAbstractImage() string
	RandomAnimalsImage() string
	RandomBusinessImage() string
	RandomCatsImage() string
	RandomCityImage() string
	RandomFoodImage() string
	RandomNightlifeImage() string
	RandomFashionImage() string
	RandomPeopleImage() string
	RandomNatureImage() string
	RandomSportsImage() string
	RandomTransportImage() string
	RandomCountryCode() string
	RandomPhoneNumber() string
	RandomPhoneNumberExt() string
	RandomJobArea() string
	RandomJobDescriptor() string
	RandomJobType() string
	RandomJobTitle() string
	RandomSemver() string
	RandomProtocol() string
	RandomAbbreviation() string
	RandomAlphanumeric() string
	RandomIpv6() string
}
